export type {
  Bout,
  Competition,
  CompetitionStatus,
  Match,
  MatchDetails,
  MatchDisqualificationEvent,
  MatchEvent,
  MatchInput,
  MatchFighter,
  MatchOutcome,
  MatchScoreAdjustmentEvent,
  MatchScoreEvent,
  MatchExchangeDetails,
  MatchTimeoutEvent,
  MatchWarningEvent,
  NewBoutInput,
  Participant,
  RankingEntry,
} from "@hema/competition-api";
